name: Manual API Deployment
on:
  workflow_dispatch:
    inputs:
      commit-sha:
        description: 'Commit SHA to deploy'
        required: true

concurrency:
  group: api-manual-deploy
  cancel-in-progress: false

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: kavachat-api

jobs:
  build-image:
    name: Build Docker image for manual deployment
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image-name.outputs.image }}
    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit-sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials for container registry
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.REPO_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.REPO_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image name
        id: image-name
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-name.outputs.image }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-production-api:
    name: Manual deploy API to production
    needs:
      - build-image
    uses: ./.github/workflows/deploy-api.yml
    # This passes **repo secrets** which are actually not set (empty strings).
    # However, this grants access to the child workflow to read the secrets from
    # the **environment secrets**
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      environment-name: api-production
      environment-url: https://kavachat-api.production.kava.io
      image-name: ${{ needs.build-image.outputs.image-name }}
