name: Deploy API

# Ensure only 1 deployment is running at a time for each environment
concurrency:
  group: ${{ inputs.environment }}
  # Do NOT cancel in-progress deployments, ensure each deployment completes
  # before starting the next one. This allows for rollbacks to the latest most
  # stable version, instead of potentially skipping over a stable version.
  cancel-in-progress: false

on:
  # Reusable workflow to be called by other workflows
  workflow_call:
    inputs:
      image-name:
        required: true
        description: 'Full Docker image name to deploy'
        type: string
      environment:
        required: true
        description: 'Environment to deploy to'
        type: string
    # These are set in **environment** settings, not repository-wide secrets.
    # The values in the parent workflow are replaced with the values environment
    # settings of this workflow.
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: 'AWS Access Key ID for ECS deployment'
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: 'AWS Secret Access Key for ECS deployment'

env:
  AWS_REGION: us-east-1
  ECS_SERVICE: kavachat-api
  ECS_CLUSTER: kavachat
  # This is the family name of the task definition, excluding revision to get
  # the latest ACTIVE revision. Fetch the -template task definition which is
  # managed by terraform.
  ECS_TASK_DEFINITION_FAMILY_TEMPLATE: kavachat-api-template
  ECS_TASK_DEFINITION_FAMILY: kavachat-api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # Ensure the inputs are set
    if: ${{ inputs.image-name != '' && inputs.environment != '' }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Output image name
        run: echo "Deploying Docker image '${{ inputs.image-name }}' to '${{ inputs.environment }}'"

      - name: Configure AWS credentials for service deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # These are set in the **environment** settings, not repository-wide
          # secrets. This allows for different credentials for different
          # environments.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_DEFINITION_FAMILY_TEMPLATE }} \
            --query taskDefinition > task-definition.json

      - name: Update image ID in Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        # Does not support changing task family name
        with:
          task-definition: task-definition.json
          # Only modify the image, nothing else
          image: ${{ inputs.image-name }}
          # Container name matches service name
          container-name: ${{ env.ECS_SERVICE }}

      - name: Rename task family in task json file
        # taskDefinitionArn does not need to be changed as it is only from query
        # and not used for registering new task definitions
        run: |
          mv ${{ steps.task-def.outputs.task-definition }} task-definition.json.bak
          jq '.family = "${{ env.ECS_TASK_DEFINITION_FAMILY }}"' task-definition.json.bak > ${{ steps.task-def.outputs.task-definition }}

      - name: Output updated task definition
        run: cat ${{ steps.task-def.outputs.task-definition }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          # Registers new task definition
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
