name: Client Unit Test CI
on: [push]

jobs:
  client-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: npm install
        run: cd ./client && npm install
      - name: tests
        run: cd ./client && npm test
