name: Client Playwright Tests
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_BASE_URL: https://api.openai.com/v1
    steps:
    - uses: actions/checkout@v4
    
    # Setup Node.js
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    
    # Setup Go
    - uses: actions/setup-go@v4
      with:
        go-version: 1.23
    
    # Install Node.js dependencies
    - name: Install dependencies
      run: npm ci
    
    # Install Playwright Browsers
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    # Run Playwright tests
    - name: Run Playwright tests
      run: npx playwright test
